name: KooponCraft Health Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: cd server && npm install

      # - name: Run linter
      #   run: npm run lint

      - name: Start the application
        run: |
          cd server && npm start &
          echo $! > .pidfile
          sleep 30

      - name: Check if application is running
        run: |
          if ! curl -s http://127.0.0.1:5500 > /dev/null; then
            echo "Server is not running"
            exit 1
          fi

      - name: Check for frontend load
        run: |
          if ! curl -s http://127.0.0.1:5500 | grep -q '<div class="welcome-area pt-120">'; then
            echo "Frontend not loaded properly"
            exit 1
          fi

      - name: Stop the application
        if: always()
        run: kill $(cat .pidfile)
